$('.first').owlCarousel({
    loop:true,
    margin:15,
    nav:false,
    autoplayHoverPause:true,
    autoplay:1000,
    paginatino:true,
    responsive:{
        0:{
            items:1
        },
        600:{
            items:3
        },
        1000:{
            items:1
        }
    }
})

$('.secondary').owlCarousel({
    loop:true,
    margin:15,
    nav:true,
    autoplay:1000,
    responsive:{
        0:{
            items:1
        },
        600:{
            items:3
        },
        1000:{
            items:4
        }
    }
})

